apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demoapp-ingress
  annotations:
    kubernetes.io/ingress.class: "azure-application-gateway"
spec:
  rules:
  - host: "demoapp.techade.org"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: demoapp-svc
            port:
              number: 80
  
