apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app-container
        image: ${{ secrets.ACR }}.azurecr.io/demonodejsapp:${{ github.sha }}
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"


---


apiVersion: v1
kind: Service
metadata:
  name: demoapps-svc
  labels:
    app: demoapps-svc
spec:
  type: ClusterIP
  selector:
    app: demo-app
  ports:
    - port: 80           
      targetPort: 8080  
      protocol: TCP      

