name: docker_build_ACR

on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
    build-to-docker:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Azure Login
        uses: Azure/login@v2.2.0
        with:
            client-id: 404bf69f-9284-4e13-b187-a6b0f98ffd14
            tenant-id: 44e0fe4b-405f-4678-bcb4-a6063b67f6b3
            subscription-id: 7f112840-74e8-45d2-8eb8-4d4f4248f2ca
            enable-AzPSSession: true
            audience: api://AzureADTokenExchange
            auth-type: IDENTITY  
          
      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
            username: ${{ secrets.ACR_USERNAME }}
            password: ${{ secrets.ACR_PASS }}
            login-server: dockercr01.azurecr.io

      - name: build_image
        run: |
                docker build -t demonodeapp .
                docker tag demonodeapp webappaksregistry.azurecr.io/demonodejsapp:v1
                docker push webappaksregistry.azurecr.io/demonodejsapp:v1
