name: docker_build_ACR

on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
    build-to-docker:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Azure Login
        uses: Azure/login@v2.2.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show  
          
      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
            username: ${{ secrets.ACR_USERNAME }}
            password: ${{ secrets.ACR_PASS }}
            login-server: dockercr01.azurecr.io

      - name: build_image
        run: |
                docker build -t demonodeapp .
                docker tag demonodeapp webappaksregistry.azurecr.io/demonodejsapp:v1
                docker push webappaksregistry.azurecr.io/demonodejsapp:v1
