name: build_IMG

on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
    build-to-acr:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
                  
      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
            username: ${{ secrets.ACR_USERNAME }}
            password: ${{ secrets.ACR_PASS }}
            login-server: ${{ secrets.ACR }}.azurecr.io

      - name: build_image
        run: |
                docker build -t demonodeapp .
                docker tag demonodeapp ${{ secrets.ACR }}.azurecr.io/demonodejsapp:${{ github.sha }}
                docker push ${{ secrets.ACR }}.azurecr.io/demonodejsapp:${{ github.sha }}


    deploy-to-AKS:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Set up AKS credentials
        run: |
                az aks get-credentials --resource-group ${{ secrets.RG }} --name ${{ secrets.AKS }}

      - name: Deploy to AKS
        run: |
                sed -i 's|image: .*|image: '"${{ secrets.ACR }}.azurecr.io/demonodejsapp:${{ github.sha }}"'|' mavendeploy.yaml
                kubectl apply -f ingress.yml
